export const users = [
  { email: "admin@email.com", password: "password1", role: "admin" },
  {
    email: "student@email.com",
    password: "password1",
    role: "student",
    program: "diploma",
    firstName: "John",
    lastName: "Doe",
    phone: "123-456-7890",
    dob: "1990-01-15",
    username: "johndoe",
    studentID: "STU12345",
  },
  {
    email: "student1@email.com",
    password: "password1",
    role: "student",
    program: "post diploma",
    firstName: "Alice",
    lastName: "Smith",
    phone: "987-654-3210",
    dob: "1995-03-20",
    username: "alicesmith",
    studentID: "STU67890",
  },
  {
    email: "student2@email.com",
    password: "password1",
    role: "student",
    program: "post diploma",
    firstName: "Bob",
    lastName: "Johnson",
    phone: "555-123-4567",
    dob: "1988-07-10",
    username: "bobjohnson",
    studentID: "STU24680",
  },
  {
    email: "student3@email.com",
    password: "password1",
    role: "student",
    program: "certificate",
    firstName: "Eva",
    lastName: "Davis",
    phone: "444-999-8888",
    dob: "1992-12-05",
    username: "evadavis",
    studentID: "STU13579",
  },
  {
    email: "student4@email.com",
    password: "password1",
    role: "student",
    program: "diploma",
    firstName: "Michael",
    lastName: "Brown",
    phone: "777-111-2222",
    dob: "1985-06-30",
    username: "michaelbrown",
    studentID: "STU97531",
  },
  {
    email: "student5@email.com",
    password: "password1",
    role: "student",
    program: "certificate",
    firstName: "Sophia",
    lastName: "Wilson",
    phone: "222-777-3333",
    dob: "1998-09-25",
    username: "sophiawilson",
    studentID: "STU86420",
  },
];
